# Generated by Django 2.1.5 on 2019-01-26 21:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0001_initial'),
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('main_photo', models.ImageField(upload_to='photos/projects/%Y/%m')),
                ('zone', models.CharField(choices=[('Norte', 'nor'), ('Centro', 'cen'), ('Sur', 'sur'), ('Todas', 'all')], max_length=4)),
                ('location_lat', models.FloatField()),
                ('location_long', models.FloatField()),
                ('is_active', models.BooleanField(default=False)),
                ('budget_allocated', models.FloatField()),
                ('dollar', models.FloatField()),
                ('plazo', models.FloatField(verbose_name='Plazo ejecución')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contractors.Contractor')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pms.ProjectManager')),
            ],
        ),
    ]
