# Generated by Django 2.1.5 on 2019-01-26 22:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_auto_20190126_2243'),
        ('pms', '0002_auto_20190126_2243'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('main_photo', models.ImageField(upload_to='photos/projects/%Y/%m')),
                ('scope', models.CharField(choices=[('fuel', 'Combustibles'), ('imag', 'Imagen'), ('cons', 'Consultoría'), ('lice', 'Permisos y Licencias'), ('desi', 'Diseños')], max_length=50)),
                ('zone', models.CharField(choices=[('nor', 'Norte'), ('cen', 'Centro'), ('sur', 'Sur'), ('all', 'Todas')], max_length=4)),
                ('location_lat', models.FloatField()),
                ('location_long', models.FloatField()),
                ('is_active', models.BooleanField(default=False)),
                ('budget_allocated', models.FloatField()),
                ('dollar', models.FloatField()),
                ('goal_time', models.FloatField()),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contractors.Contractor')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pms.ProjectManager')),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_manager',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
