# Generated by Django 2.1.5 on 2019-01-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190126_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(choices=[('BAR', 'Barranquilla'), ('MED', 'Medellín'), ('CAR', 'Cartagena'), ('BOG', 'Bogota DC'), ('STA', 'Santa Marta'), ('CAL', 'Cali'), ('PAS', 'Pasto'), ('VIL', 'Villavicencio'), ('IBG', 'Ibague')], default='BOG', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('ATL', 'Atlántico'), ('ANT', 'Antioquia'), ('BOL', 'Bolivar'), ('CUND', 'Cundinamarca'), ('MAG', 'Magdalena'), ('VAL', 'Valle del Cauca'), ('NAR', 'Nariño'), ('MET', 'Meta'), ('HUI', 'Huila')], default='CUN', max_length=30),
        ),
    ]
