# Generated by Django 2.1.5 on 2019-01-30 17:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190130_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='GanttImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fascia_completion', models.DecimalField(decimal_places=1, max_digits=2)),
                ('spreader_completion', models.DecimalField(decimal_places=1, max_digits=2)),
                ('paint_completion', models.DecimalField(decimal_places=1, max_digits=2)),
                ('signage_completion', models.DecimalField(decimal_places=1, max_digits=2)),
                ('fundation_completion', models.DecimalField(decimal_places=1, max_digits=2)),
                ('lifting_completion', models.DecimalField(decimal_places=1, max_digits=2)),
                ('report_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Project')),
            ],
        ),
    ]
