# Generated by Django 2.1.5 on 2019-01-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_ganttimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganttimage',
            name='fascia_completion',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='ganttimage',
            name='fundation_completion',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='ganttimage',
            name='lifting_completion',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='ganttimage',
            name='paint_completion',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='ganttimage',
            name='signage_completion',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='ganttimage',
            name='spreader_completion',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
