# Generated by Django 2.1.5 on 2019-01-31 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190130_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fascia_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='project',
            name='fascia_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('fun', 'Cimentación'), (' ', 'Sin prescedencia'), ('spr', 'Spreader'), ('pan', 'Pintura'), ('fas', 'Fascia'), ('sig', 'Rótulos')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='fascia_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='project',
            name='fundation_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='project',
            name='fundation_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('fun', 'Cimentación'), (' ', 'Sin prescedencia'), ('spr', 'Spreader'), ('pan', 'Pintura'), ('fas', 'Fascia'), ('sig', 'Rótulos')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='fundation_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='project',
            name='lifting_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='project',
            name='lifting_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('fun', 'Cimentación'), (' ', 'Sin prescedencia'), ('spr', 'Spreader'), ('pan', 'Pintura'), ('fas', 'Fascia'), ('sig', 'Rótulos')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='lifting_star',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='project',
            name='paint_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='project',
            name='paint_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('fun', 'Cimentación'), (' ', 'Sin prescedencia'), ('spr', 'Spreader'), ('pan', 'Pintura'), ('fas', 'Fascia'), ('sig', 'Rótulos')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='paint_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='project',
            name='signage_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='project',
            name='signage_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('fun', 'Cimentación'), (' ', 'Sin prescedencia'), ('spr', 'Spreader'), ('pan', 'Pintura'), ('fas', 'Fascia'), ('sig', 'Rótulos')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='signage_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
