# Generated by Django 2.1.5 on 2019-01-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20190131_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='lifting_star',
            new_name='lifting_start',
        ),
        migrations.AlterField(
            model_name='project',
            name='fascia_parent',
            field=models.CharField(choices=[('sig', 'Rótulos'), ('pan', 'Pintura'), ('fun', 'Cimentación'), ('spr', 'Spreader'), ('fas', 'Fascia'), (' ', 'Sin prescedencia'), ('lif', 'Izaje')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='fundation_parent',
            field=models.CharField(choices=[('sig', 'Rótulos'), ('pan', 'Pintura'), ('fun', 'Cimentación'), ('spr', 'Spreader'), ('fas', 'Fascia'), (' ', 'Sin prescedencia'), ('lif', 'Izaje')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='lifting_parent',
            field=models.CharField(choices=[('sig', 'Rótulos'), ('pan', 'Pintura'), ('fun', 'Cimentación'), ('spr', 'Spreader'), ('fas', 'Fascia'), (' ', 'Sin prescedencia'), ('lif', 'Izaje')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='paint_parent',
            field=models.CharField(choices=[('sig', 'Rótulos'), ('pan', 'Pintura'), ('fun', 'Cimentación'), ('spr', 'Spreader'), ('fas', 'Fascia'), (' ', 'Sin prescedencia'), ('lif', 'Izaje')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='signage_parent',
            field=models.CharField(choices=[('sig', 'Rótulos'), ('pan', 'Pintura'), ('fun', 'Cimentación'), ('spr', 'Spreader'), ('fas', 'Fascia'), (' ', 'Sin prescedencia'), ('lif', 'Izaje')], default='', max_length=20),
        ),
    ]
