# Generated by Django 2.1.5 on 2019-01-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190131_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fascia_parent',
            field=models.CharField(choices=[('pan', 'Pintura'), ('sig', 'Rótulos'), ('fas', 'Fascia'), ('fun', 'Cimentación'), ('lif', 'Izaje'), (' ', 'Sin prescedencia'), ('spr', 'Spreader')], default=' ', max_length=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='fundation_parent',
            field=models.CharField(choices=[('pan', 'Pintura'), ('sig', 'Rótulos'), ('fas', 'Fascia'), ('fun', 'Cimentación'), ('lif', 'Izaje'), (' ', 'Sin prescedencia'), ('spr', 'Spreader')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='lifting_parent',
            field=models.CharField(choices=[('pan', 'Pintura'), ('sig', 'Rótulos'), ('fas', 'Fascia'), ('fun', 'Cimentación'), ('lif', 'Izaje'), (' ', 'Sin prescedencia'), ('spr', 'Spreader')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='paint_parent',
            field=models.CharField(choices=[('pan', 'Pintura'), ('sig', 'Rótulos'), ('fas', 'Fascia'), ('fun', 'Cimentación'), ('lif', 'Izaje'), (' ', 'Sin prescedencia'), ('spr', 'Spreader')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='signage_parent',
            field=models.CharField(choices=[('pan', 'Pintura'), ('sig', 'Rótulos'), ('fas', 'Fascia'), ('fun', 'Cimentación'), ('lif', 'Izaje'), (' ', 'Sin prescedencia'), ('spr', 'Spreader')], default=' ', max_length=20),
        ),
    ]
