# Generated by Django 2.1.5 on 2019-01-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20190131_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fascia_parent',
            field=models.CharField(choices=[('fas', 'Fascia'), ('spr', 'Spreader'), (' ', 'Sin prescedencia'), ('lif', 'Izaje'), ('fun', 'Cimentación'), ('sig', 'Rótulos'), ('pan', 'Pintura')], default=' ', max_length=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='fundation_parent',
            field=models.CharField(choices=[('fas', 'Fascia'), ('spr', 'Spreader'), (' ', 'Sin prescedencia'), ('lif', 'Izaje'), ('fun', 'Cimentación'), ('sig', 'Rótulos'), ('pan', 'Pintura')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='lifting_parent',
            field=models.CharField(choices=[('fas', 'Fascia'), ('spr', 'Spreader'), (' ', 'Sin prescedencia'), ('lif', 'Izaje'), ('fun', 'Cimentación'), ('sig', 'Rótulos'), ('pan', 'Pintura')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='paint_parent',
            field=models.CharField(choices=[('fas', 'Fascia'), ('spr', 'Spreader'), (' ', 'Sin prescedencia'), ('lif', 'Izaje'), ('fun', 'Cimentación'), ('sig', 'Rótulos'), ('pan', 'Pintura')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='signage_parent',
            field=models.CharField(choices=[('fas', 'Fascia'), ('spr', 'Spreader'), (' ', 'Sin prescedencia'), ('lif', 'Izaje'), ('fun', 'Cimentación'), ('sig', 'Rótulos'), ('pan', 'Pintura')], default=' ', max_length=20),
        ),
    ]
