# Generated by Django 2.1.5 on 2019-01-31 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20190131_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fascia_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('spr', 'Spreader'), ('pan', 'Pintura'), ('fas', 'Fascia'), (' ', 'Sin prescedencia'), ('sig', 'Rótulos'), ('fun', 'Cimentación')], default=' ', max_length=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='fundation_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('spr', 'Spreader'), ('pan', 'Pintura'), ('fas', 'Fascia'), (' ', 'Sin prescedencia'), ('sig', 'Rótulos'), ('fun', 'Cimentación')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='lifting_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('spr', 'Spreader'), ('pan', 'Pintura'), ('fas', 'Fascia'), (' ', 'Sin prescedencia'), ('sig', 'Rótulos'), ('fun', 'Cimentación')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='paint_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('spr', 'Spreader'), ('pan', 'Pintura'), ('fas', 'Fascia'), (' ', 'Sin prescedencia'), ('sig', 'Rótulos'), ('fun', 'Cimentación')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='signage_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('spr', 'Spreader'), ('pan', 'Pintura'), ('fas', 'Fascia'), (' ', 'Sin prescedencia'), ('sig', 'Rótulos'), ('fun', 'Cimentación')], default=' ', max_length=20),
        ),
    ]
