# Generated by Django 2.1.5 on 2019-01-26 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contractor_logo', models.ImageField(upload_to='photos/contractors/%Y/%m')),
                ('scope', models.CharField(choices=[('Combustibles', 'fuel'), ('Imgen', 'imge'), ('Consultoría', 'cons'), ('Licencias', 'lice'), ('Diseños', 'desi')], max_length=4)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
