# Generated by Django 2.1.5 on 2019-01-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='scope',
            field=models.CharField(choices=[('fuel', 'Combustibles'), ('imag', 'Imagen'), ('cons', 'Consultoría'), ('lice', 'Permisos y Licencias'), ('desi', 'Diseños')], max_length=40),
        ),
    ]
